{% set goname = "github.com/louketo/louketo-proxy" %}
{% set version = "1.0.0" %}

{% set name = "keycloak-gatekeeper" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/{{ version }}.tar.gz
  sha256: 6bf29b670b4ab5de577aa419876749cd72a172e02a14d165f156b42bd791ad0b

build:
  number: 0
  script:
    - make

requirements:
  build:
    - {{ compiler("go") }}
    - make

test:
  source_files:
    - bin/
  commands:
    - bash -c "bin/louketo-proxy -v"

about:
  home: https://github.com/louketo/louketo-proxy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'An adapter for use with OpenID Connect that supports both access tokens in a browser cookie or bearer tokens'
  description: |
    Keycloak is an open source Identity and Access Management solution aimed
    at modern applications and services. It makes it easy to secure applications
    and services with little to no code. Some of its features include Single-Sign On,
    Identity Brokering and Social Login, User Federation and Client Adapters.
  doc_url: https://www.keycloak.org/docs/latest/securing_apps/index.html#_keycloak_generic_adapter
  dev_url: https://github.com/louketo/louketo-proxy

extra:
  recipe-maintainers:
    - adbeda
    - sodre
    - rluria14
    - oblute
    - ndmaxar
