travis:
  secure:
    BINSTAR_TOKEN: Yu+d0JIRR2cXo24P6Ylo94O43XXY8y9Ysq9zuTh80NKbg9u5zIADTLnWJUrD6EyWRhdcr5Khjflgz/Ug6v5wQOwQU2VVM0H940OtgCyDdpQX32YkCQlbXjjahw9GkLWHParykvcMDfqsr+G94h2czLn5sy1X7b+NhP7WrymIY/heEtQUetoeB/frYjAV88hsD747CRkQC63U13snDHnNoZiPdSGqUbZMu+rKLPE+DIs02zax9gl55iZkJ3egJ7GVYm0gT/hn74oy8ek4EciJijoWZP3HEi08oKr2iLyIA4yd7Rea+CDxqsP3QUA/YXRLk6iitv/TMB4kBvOT6ixvvwnHyQ2a5qdkTam+HidXYsEteRYHsEEKQ+SibZrsD6myG0MtiZ+YPVz9pWOHrbB3A/BTkJTOFelL3XlQKmpX3w0VQaghIyIiKzySqy9dlwP4Um/5+UwH6WP1jFe74aLUXBv4jX4NSrQPu0LNxckBVYlOUc3mwqHUs9HUAZGxIs/Eu4I2uh6WrfTdENAdra/CgaDXRCYLlSclertlrysUckdAuMTJ12zCPUfX22VbmLWOClVyjbeiP0lycY9h3pdvZ53vfTyBubBBEmpMgYPHcTEeXlRBWFsH6xZxtACA3KZdE35RrktAkVh8mseZXbHjRd7x9NzawMl8ioQNozRosic=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
